### ISSUE TITLE
No problems, just a question to check if it's possible

### ISSUE THREAD

**Issue by Maureks** [Gubner/decrypto#1]
Is it possible for the Hack ATM option , to only appear on the ATM when the player has the items with him? What can I do?
Thanks in advance
Nice Work btw !

**Comment by Gubner** [comment]
Great idea - I updated client.lua for this.
https://github.com/Gubner/decrypto/commit/952c63b55df5a2366912be863e75596ff55fd7ef

**Comment by Maureks** [comment]
Fantastic! Thank you so much !
